### PR TITLE
Caleb - Update User Controllers and User Table so Admins can toggle roles of different users for Professor, Students, Admins (plus tests)

### LINKED ISSUE #12: FEATURE: Show individual user roles on admin User Table
# User Story

* As an admin
* I can see what roles a user has
* so that I can differentiate students and professors

### Discussion

We have a current User table to show the logged in users of the application. We want to add roles to this table to visually see which users are students vs. professors. 

As an example, here is the admin User table from proj-gauchoride:

Screenshot 2024-11-13 at 1 44 59 PM

We want to make ours look similar to this, except for the Admin/Student/Professor Roles. Toggling roles could also be an issue to work on after this if you get time!

### Acceptance Criteria

- [x] Admins can view the roles of different users on the User Table

Optional future issue:
- [x] Admins can toggle user roles

### Implementation Todos

Frontend/Backend changes:
- [x] The User Table includes boolean columns for each of the roles (student, professor, admin).
- [x] Based on their user roles, each row (a single user) is populated with the correct Boolean values

Testing:
- [x] Front end tests pass and there is adequate coverage
- [x] Back end tests pass and there is adequate coverage

# Hints

Compare the following files between the current `proj-rec` code base, and the `proj-gauchoride` code base.  

| proj-rec | proj-gauchoride | What to look for |
|---------|-----------------|------------------|
| [User.java](https://github.com/ucsb-cs156/proj-rec/blob/main/src/main/java/edu/ucsb/cs156/rec/entities/User.java) | [User.java](https://github.com/ucsb-cs156/proj-gauchoride/blob/main/src/main/java/edu/ucsb/cs156/gauchoride/entities/User.java) | Look at the extra fields for the roles |
| [SecurityConfig.java](https://github.com/ucsb-cs156/proj-rec/blob/main/src/main/java/edu/ucsb/cs156/rec/config/SecurityConfig.java) | [SecurityConfig.java](https://github.com/ucsb-cs156/proj-gauchoride/blob/main/src/main/java/edu/ucsb/cs156/gauchoride/config/SecurityConfig.java) | Look at the code that handles the roles |
| (not present) | [RoleInterceptor.java](https://github.com/ucsb-cs156/proj-gauchoride/blob/main/src/main/java/edu/ucsb/cs156/gauchoride/interceptors/RoleInterceptor.java) | This is an extra file you'll need  to handle dynamically changing roles |
| (not present) | [RoleInterceptorConfig.java](https://github.com/ucsb-cs156/proj-gauchoride/blob/main/src/main/java/edu/ucsb/cs156/gauchoride/interceptors/RoleInterceptorConfig.java) | This is an extra file you'll need to handle dynamically changing roles |
| [UsersController.java](https://github.com/ucsb-cs156/proj-rec/blob/main/src/main/java/edu/ucsb/cs156/rec/controllers/UsersController.java) | [UsersController.java](https://github.com/ucsb-cs156/proj-gauchoride/blob/main/src/main/java/edu/ucsb/cs156/gauchoride/controllers/UsersController.java) | Look at the methods for toggling roles |
| [usersFixtures.js](https://github.com/ucsb-cs156/proj-rec/blob/main/frontend/src/fixtures/usersFixtures.js) | [usersFixtures.js](https://github.com/ucsb-cs156/proj-gauchoride/blob/main/frontend/src/fixtures/usersFixtures.js) | note the extra fields for the roles |
| [UsersTable.js](https://github.com/ucsb-cs156/proj-gauchoride/blob/main/frontend/src/main/components/Users/UsersTable.js)) | [UsersTable.js](https://github.com/ucsb-cs156/proj-gauchoride/blob/main/frontend/src/main/components/Users/UsersTable.js) | Code for toggling roles |

### PR DESCRIPTION
**Pull request by caleb-stahl**
MERGE AFTER #60 

Closes #12 

For this PR, I added a few frontend and backend changes building off #56  and finishing #12. 

If you log in as an admin, you will notice a few changes to the Users Table: 
Screenshot 2024-11-22 at 6 39 34 PM
As well as a few new swagger endpoints:
Screenshot 2024-11-22 at 6 40 18 PM

Dokku deployment: https://proj-rec-caleb-stahl.dokku-08.cs.ucsb.edu

NOTE: the buttons are not functional (that is something we can add in the future), but the endpoints are working. Also, please merge #60 before this.

### CODE REVIEW

**Comment by Division7** [comment]
Heads up, you likely should roll back your changes to `package.json` and remove your chromatic project token.

**Comment by caleb-stahl** [comment]
> Heads up, you likely should roll back your changes to `package.json` and remove your chromatic project token.

Thanks for the catch. Meant to take that out. Just updated it

**Review by obenedek20 — DISMISSED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM!

**Pull request merged**
